// Generated by gencpp from file programming_robots_with_ros/WordCount.msg
// DO NOT EDIT!


#ifndef PROGRAMMING_ROBOTS_WITH_ROS_MESSAGE_WORDCOUNT_H
#define PROGRAMMING_ROBOTS_WITH_ROS_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <programming_robots_with_ros/WordCountRequest.h>
#include <programming_robots_with_ros/WordCountResponse.h>


namespace programming_robots_with_ros
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace programming_robots_with_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::programming_robots_with_ros::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::programming_robots_with_ros::WordCount&) { return value(); }
};

template<>
struct DataType< ::programming_robots_with_ros::WordCount > {
  static const char* value()
  {
    return "programming_robots_with_ros/WordCount";
  }

  static const char* value(const ::programming_robots_with_ros::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::programming_robots_with_ros::WordCountRequest> should match 
// service_traits::MD5Sum< ::programming_robots_with_ros::WordCount > 
template<>
struct MD5Sum< ::programming_robots_with_ros::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::programming_robots_with_ros::WordCount >::value();
  }
  static const char* value(const ::programming_robots_with_ros::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::programming_robots_with_ros::WordCountRequest> should match 
// service_traits::DataType< ::programming_robots_with_ros::WordCount > 
template<>
struct DataType< ::programming_robots_with_ros::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::programming_robots_with_ros::WordCount >::value();
  }
  static const char* value(const ::programming_robots_with_ros::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::programming_robots_with_ros::WordCountResponse> should match 
// service_traits::MD5Sum< ::programming_robots_with_ros::WordCount > 
template<>
struct MD5Sum< ::programming_robots_with_ros::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::programming_robots_with_ros::WordCount >::value();
  }
  static const char* value(const ::programming_robots_with_ros::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::programming_robots_with_ros::WordCountResponse> should match 
// service_traits::DataType< ::programming_robots_with_ros::WordCount > 
template<>
struct DataType< ::programming_robots_with_ros::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::programming_robots_with_ros::WordCount >::value();
  }
  static const char* value(const ::programming_robots_with_ros::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROGRAMMING_ROBOTS_WITH_ROS_MESSAGE_WORDCOUNT_H
